version: '3.9'

services:
  app:
    container_name: apisc-app
    build: .
    command: uvicorn --factory api.app:create_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code/
    environment:
      POSTGRES_HOST: db
    networks:
      - backend
    ports:
      - 8000:8000
    depends_on:
      - db_test

  db_test:
    container_name: apisc-db-test
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    networks:
      - backend
    ports:
      - 5433:5432

networks:
  backend:
    driver: bridge

