version: '3.9'

services:
  app:
    container_name: apisc-app
    build: .
    command: uvicorn --factory api.app:create_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code/
    environment:
      POSTGRES_HOST: db
    networks:
      - backend
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    container_name: apisc-db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    networks:
      - backend
    ports:
      - 5432:5432

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
