version: '3.9'

services:
  app:
    container_name: apisc-app
    build: .
    command: uvicorn --factory api.app:create_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code/
    environment:
      POSTGRES_HOST: db
    networks:
      - backend
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    container_name: apisc-db
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - backend
    ports:
      - 5432:5432

  db_test:
    container_name: apisc-db-test
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
    networks:
      - backend
    ports:
      - 5433:5432

  pgadmin:
    container_name: apisc-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    networks:
      - backend
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin:

networks:
  backend:
    driver: bridge
