name: Docker API Tests


on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "set up python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: "build and start containers"
        run: docker compose -f docker-compose-ci.yaml up -d --build

      - name: "sleep for a bit"
        run: sleep 10

      - name: "install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root --no-interaction --no-ansi

      - name: "run tests"
        run: pytest
